/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author syeda
 */
public class CustomerHomePage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerHomePage
     */
    public CustomerHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Transaction = new javax.swing.JButton();
        Bills = new javax.swing.JButton();
        Loan = new javax.swing.JButton();
        Statement = new javax.swing.JButton();
        Notification = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Statement1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 450));
        setMinimumSize(new java.awt.Dimension(750, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Customer HomePage");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(272, 35, 352, 43);

        Transaction.setBackground(new java.awt.Color(0, 102, 204));
        Transaction.setForeground(new java.awt.Color(255, 255, 255));
        Transaction.setText("Made Transaction ");
        Transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionActionPerformed(evt);
            }
        });
        getContentPane().add(Transaction);
        Transaction.setBounds(292, 151, 301, 23);

        Bills.setBackground(new java.awt.Color(0, 102, 204));
        Bills.setForeground(new java.awt.Color(255, 255, 255));
        Bills.setText("Pay Bills");
        Bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillsActionPerformed(evt);
            }
        });
        getContentPane().add(Bills);
        Bills.setBounds(292, 186, 301, 23);

        Loan.setBackground(new java.awt.Color(0, 102, 204));
        Loan.setForeground(new java.awt.Color(242, 242, 242));
        Loan.setText("Request Loan");
        Loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanActionPerformed(evt);
            }
        });
        getContentPane().add(Loan);
        Loan.setBounds(292, 221, 301, 23);

        Statement.setBackground(new java.awt.Color(0, 102, 204));
        Statement.setForeground(new java.awt.Color(255, 255, 255));
        Statement.setText("View Profile");
        Statement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatementActionPerformed(evt);
            }
        });
        getContentPane().add(Statement);
        Statement.setBounds(290, 290, 301, 23);

        Notification.setText("Notification");
        Notification.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationActionPerformed(evt);
            }
        });
        getContentPane().add(Notification);
        Notification.setBounds(531, 352, 90, 20);

        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(6, 6, 72, 23);

        Statement1.setBackground(new java.awt.Color(0, 102, 204));
        Statement1.setForeground(new java.awt.Color(255, 255, 255));
        Statement1.setText("View Statement");
        Statement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Statement1ActionPerformed(evt);
            }
        });
        getContentPane().add(Statement1);
        Statement1.setBounds(292, 256, 301, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.setMaximumSize(new java.awt.Dimension(650, 400));
        jLabel5.setMinimumSize(new java.awt.Dimension(650, 400));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.dispose();
new CustomerLogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void TransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionActionPerformed
        this.dispose();
        new TransactionPage().setVisible(true);
    }//GEN-LAST:event_TransactionActionPerformed

    private void BillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillsActionPerformed
      this.dispose();
      new PaymentsPage().setVisible(true);
    }//GEN-LAST:event_BillsActionPerformed

    private void LoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanActionPerformed
this.dispose();
new CustomerLoanPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LoanActionPerformed

    private void StatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatementActionPerformed
       this.dispose();
       new ProfilePage().setVisible(true);
    }//GEN-LAST:event_StatementActionPerformed

    private void NotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationActionPerformed
        this.dispose();
        new Notification().setVisible(true);
    }//GEN-LAST:event_NotificationActionPerformed

    private void Statement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Statement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Statement1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bills;
    private javax.swing.JButton Loan;
    private javax.swing.JButton Notification;
    private javax.swing.JButton Statement;
    private javax.swing.JButton Statement1;
    private javax.swing.JButton Transaction;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
